/**
 * The starting catalog, inserted the first time the database is created.
 *
 * Edit freely — these rows are only a starting point. Once the database exists
 * the seeder leaves it alone, so changes made through the database (or a future
 * admin screen) are never overwritten by a restart. To re-seed from this file,
 * delete `data/heartdog.db` and start the server again.
 *
 * Prices are integer cents to avoid floating point money entirely.
 */

export interface SeedProduct {
  slug: string;
  name: string;
  botanical_name: string;
  category: 'Vegetables' | 'Herbs' | 'Flowers' | 'Collections';
  blurb: string;
  description: string;
  price_cents: number;
  seed_count: string;
  days_to_maturity: string;
  sun: string;
  spacing: string;
  planting_depth: string;
  height: string;
  origin_note: string;
  stock: number;
  featured: boolean;
  accent: string;
  motif: string;
}

export const SEED_CATALOG: SeedProduct[] = [
  {
    slug: 'cherokee-purple-tomato',
    name: 'Cherokee Purple Tomato',
    botanical_name: 'Solanum lycopersicum',
    category: 'Vegetables',
    blurb: 'Dusky rose shoulders, a deep smoky sweetness, and the best slicing tomato we grow.',
    description:
      'Cherokee Purple slices open a deep brick red with green-shouldered marbling and tastes like a tomato remembering an older summer — low acid, almost winey, with a finish that lingers. Fruits run 10 to 12 ounces on indeterminate vines that will happily climb past six feet if you give them something to hold. Stake or cage early; the plants get heavy fast once fruit sets. Best picked at the moment the shoulders soften, not before.',
    price_cents: 395,
    seed_count: '25 seeds',
    days_to_maturity: '80-90 days',
    sun: 'Full sun',
    spacing: '24-36 in.',
    planting_depth: '1/4 in.',
    height: '6-9 ft. vine',
    origin_note: 'Passed down through Tennessee growers and credited to the Cherokee people.',
    stock: 140,
    featured: true,
    accent: '#7d4b62',
    motif: 'tomato',
  },
  {
    slug: 'brandywine-tomato',
    name: 'Brandywine Tomato',
    botanical_name: 'Solanum lycopersicum',
    category: 'Vegetables',
    blurb: 'The old Amish beefsteak that every heirloom tomato is still measured against.',
    description:
      'Enormous pink beefsteaks, often a full pound apiece, on distinctive potato-leaf vines. Brandywine is not a heavy producer and it takes its time, but a single perfect fruit on a slice of bread in August is the whole argument for growing your own. Give it rich soil, steady water, and patience. Fruits can crown and crack in a wet spell — pick a touch early and finish them on the counter.',
    price_cents: 395,
    seed_count: '25 seeds',
    days_to_maturity: '85-100 days',
    sun: 'Full sun',
    spacing: '24-36 in.',
    planting_depth: '1/4 in.',
    height: '6-8 ft. vine',
    origin_note: 'In circulation since the 1880s, long associated with Pennsylvania Amish gardens.',
    stock: 120,
    featured: false,
    accent: '#a8536a',
    motif: 'tomato',
  },
  {
    slug: 'dragon-tongue-bean',
    name: 'Dragon Tongue Bush Bean',
    botanical_name: 'Phaseolus vulgaris',
    category: 'Vegetables',
    blurb: 'Ivory pods streaked in violet, tender raw and absurdly productive.',
    description:
      'A Dutch bush bean with wide flat pods, cream-colored and painted with purple streaks that vanish the moment they hit hot water. Eat them raw off the plant while you pick — the flavor is sweeter and nuttier than any green bean has a right to be. Left on the plant to dry they make a fine shelling bean. No trellis needed; the bushes hold themselves up at about knee height.',
    price_cents: 350,
    seed_count: '50 seeds',
    days_to_maturity: '55-65 days',
    sun: 'Full sun',
    spacing: '4-6 in.',
    planting_depth: '1 in.',
    height: '24 in. bush',
    origin_note: 'A Dutch heirloom, grown in Europe well before it reached American gardens.',
    stock: 200,
    featured: true,
    accent: '#6b5b95',
    motif: 'bean',
  },
  {
    slug: 'kentucky-wonder-pole-bean',
    name: 'Kentucky Wonder Pole Bean',
    botanical_name: 'Phaseolus vulgaris',
    category: 'Vegetables',
    blurb: 'The climbing bean that fed a century of porch-shelling evenings.',
    description:
      'Vigorous vines to eight feet, hung with long, meaty, faintly stringy pods that carry a deep old-fashioned bean flavor. Pick young for snaps, or let them fill out and shell them. Kentucky Wonder wants something to climb — a tripod of saplings, a length of cattle panel, the porch rail. It will find its own way up. Keep picking and it will keep setting until frost.',
    price_cents: 350,
    seed_count: '50 seeds',
    days_to_maturity: '65-75 days',
    sun: 'Full sun',
    spacing: '4-6 in.',
    planting_depth: '1 in.',
    height: '6-8 ft. vine',
    origin_note: 'Sold in American seed catalogs since at least 1864.',
    stock: 185,
    featured: false,
    accent: '#4a7c59',
    motif: 'bean',
  },
  {
    slug: 'moon-and-stars-watermelon',
    name: 'Moon and Stars Watermelon',
    botanical_name: 'Citrullus lanatus',
    category: 'Vegetables',
    blurb:
      'A dark rind scattered with golden stars and one big moon. Nearly lost, then found again.',
    description:
      'Twenty-pound melons with deep green rinds freckled in yellow — small stars all over, and usually one moon-sized blotch. The foliage is spotted too. Sweet red flesh, brown seeds, and a vining habit that will run fifteen feet if you let it. This variety essentially disappeared from commerce until a Missouri grower turned up a surviving planting in 1981. Give it heat, room, and a long season.',
    price_cents: 425,
    seed_count: '15 seeds',
    days_to_maturity: '95-100 days',
    sun: 'Full sun',
    spacing: '36-48 in.',
    planting_depth: '1 in.',
    height: '12-15 ft. vine',
    origin_note: 'Nearly extinct by the 1970s; recovered from a single Missouri planting in 1981.',
    stock: 90,
    featured: true,
    accent: '#2f6b4f',
    motif: 'melon',
  },
  {
    slug: 'jimmy-nardello-pepper',
    name: 'Jimmy Nardello Sweet Pepper',
    botanical_name: 'Capsicum annuum',
    category: 'Vegetables',
    blurb: 'Long, curling, crimson, and sweeter fried than any pepper has any business being.',
    description:
      'Thin-walled red frying peppers that curl and taper to eight inches. No heat at all — just sugar and a rich fruitiness that concentrates the moment they hit a hot pan with olive oil. Prolific enough that a few plants will keep a kitchen supplied through late summer. The peppers dry well too, if you can keep from eating them first.',
    price_cents: 395,
    seed_count: '25 seeds',
    days_to_maturity: '80-90 days',
    sun: 'Full sun',
    spacing: '18-24 in.',
    planting_depth: '1/4 in.',
    height: '24-30 in.',
    origin_note: 'Carried from Basilicata, Italy to Connecticut in 1887 by the Nardello family.',
    stock: 130,
    featured: false,
    accent: '#c0442f',
    motif: 'pepper',
  },
  {
    slug: 'california-wonder-pepper',
    name: 'California Wonder Bell Pepper',
    botanical_name: 'Capsicum annuum',
    category: 'Vegetables',
    blurb: 'The blocky green-to-red bell that made stuffed peppers a weeknight dinner.',
    description:
      'Thick-walled four-lobed bells, about four inches across, ripening from glossy green to a full sweet red if you leave them on. Sturdy upright plants hold their fruit off the ground. An honest, reliable pepper — nothing exotic, just a good yield of the shape everyone actually wants. Harvest green for crunch and heft, red for sweetness.',
    price_cents: 350,
    seed_count: '30 seeds',
    days_to_maturity: '70-75 days green, 85 red',
    sun: 'Full sun',
    spacing: '18-24 in.',
    planting_depth: '1/4 in.',
    height: '24-30 in.',
    origin_note: 'Introduced in 1928 and a garden standard ever since.',
    stock: 160,
    featured: false,
    accent: '#3f7d3f',
    motif: 'pepper',
  },
  {
    slug: 'golden-bantam-sweet-corn',
    name: 'Golden Bantam Sweet Corn',
    botanical_name: 'Zea mays',
    category: 'Vegetables',
    blurb: 'The corn that convinced America yellow sweet corn was worth eating.',
    description:
      'Eight-inch ears with deep golden kernels on sturdy five-foot stalks, usually two ears per plant. This is old-style corn sugar — real corn flavor rather than the candy sweetness of modern hybrids — and it converts to starch fast, so get it from stalk to pot the same hour if you can. Plant in blocks of at least four short rows rather than one long one; it is wind pollinated and needs the company.',
    price_cents: 375,
    seed_count: '100 seeds',
    days_to_maturity: '75-85 days',
    sun: 'Full sun',
    spacing: '8-12 in.',
    planting_depth: '1-2 in.',
    height: '5-6 ft.',
    origin_note:
      'Introduced by Burpee in 1902; before it, yellow corn was thought fit only for livestock.',
    stock: 110,
    featured: false,
    accent: '#d4a017',
    motif: 'corn',
  },
  {
    slug: 'waltham-butternut-squash',
    name: 'Waltham Butternut Squash',
    botanical_name: 'Cucurbita moschata',
    category: 'Vegetables',
    blurb: 'Dense orange flesh, a small seed cavity, and it keeps until spring.',
    description:
      'The standard butternut for good reason: uniform four-to-five pound fruits, thick necks of solid flesh, and a small seed cavity down at the bulb. Cures to a hard tan shell and stores six months in a cool dry room. The vines run long and will scramble up a fence if you would rather not give them the ground. Sweetness improves several weeks after harvest, so resist cutting into the first one.',
    price_cents: 375,
    seed_count: '20 seeds',
    days_to_maturity: '100-110 days',
    sun: 'Full sun',
    spacing: '36-48 in.',
    planting_depth: '1 in.',
    height: '10-12 ft. vine',
    origin_note: 'Bred at the Waltham Field Station in Massachusetts, released 1970.',
    stock: 125,
    featured: false,
    accent: '#c98b3a',
    motif: 'squash',
  },
  {
    slug: 'lemon-cucumber',
    name: 'Lemon Cucumber',
    botanical_name: 'Cucumis sativus',
    category: 'Vegetables',
    blurb: 'Round, pale yellow, never bitter, and the one kids will actually pick and eat.',
    description:
      'Tennis-ball-sized cucumbers that ripen to a soft lemon yellow — the name is about the look, not the flavor, which is mild, sweet, and completely free of the bitterness that makes people peel cucumbers. Thin skin, no need to peel at all. Vigorous vines produce heavily; pick at golf-to-tennis-ball size, because they turn seedy and tough if you let them go orange.',
    price_cents: 350,
    seed_count: '30 seeds',
    days_to_maturity: '60-70 days',
    sun: 'Full sun',
    spacing: '12 in.',
    planting_depth: '1/2 in.',
    height: '6-8 ft. vine',
    origin_note: 'Brought into American gardens in the 1890s.',
    stock: 175,
    featured: true,
    accent: '#d9c04a',
    motif: 'squash',
  },
  {
    slug: 'chioggia-beet',
    name: 'Chioggia Beet',
    botanical_name: 'Beta vulgaris',
    category: 'Vegetables',
    blurb: 'Cut one open and it is a candy-striped bullseye of pink and white.',
    description:
      'An Italian market beet with concentric rings of rose and white inside a plain orange-red skin — nobody expects it until the knife goes through. Milder and sweeter than a standard red beet, and it will not bleed all over everything else on the cutting board. Roast in wedges to keep the rings visible; boiling fades them to pale pink. The greens are excellent, so thin generously and eat the thinnings.',
    price_cents: 325,
    seed_count: '75 seeds',
    days_to_maturity: '55-60 days',
    sun: 'Full sun to part shade',
    spacing: '3-4 in.',
    planting_depth: '1/2 in.',
    height: '12-18 in.',
    origin_note: 'From the fishing town of Chioggia near Venice, in gardens since the 1840s.',
    stock: 190,
    featured: false,
    accent: '#c2506d',
    motif: 'root',
  },
  {
    slug: 'scarlet-nantes-carrot',
    name: 'Scarlet Nantes Carrot',
    botanical_name: 'Daucus carota',
    category: 'Vegetables',
    blurb: 'Blunt-tipped, coreless, and sweet enough to pull and eat standing in the row.',
    description:
      'Seven-inch cylindrical roots with blunt ends and almost no fibrous core — crisp, bright orange, and notably sweet, especially after a light frost. Nantes types want loose soil free of rocks; in heavy clay they fork and stunt, so work in sand or compost or grow them in a raised bed. Sow thickly and thin ruthlessly, because crowded carrots stay small.',
    price_cents: 325,
    seed_count: '500 seeds',
    days_to_maturity: '65-70 days',
    sun: 'Full sun to part shade',
    spacing: '2-3 in.',
    planting_depth: '1/4 in.',
    height: '12-16 in.',
    origin_note: 'A French Nantes selection dating to the 1850s.',
    stock: 210,
    featured: false,
    accent: '#e08214',
    motif: 'root',
  },
  {
    slug: 'rainbow-swiss-chard',
    name: 'Rainbow Swiss Chard',
    botanical_name: 'Beta vulgaris subsp. cicla',
    category: 'Vegetables',
    blurb: 'Neon stems in gold, pink, crimson and white. Cut it and it grows back.',
    description:
      'A mix of chard selections with stems in every warm color, glossy savoyed leaves, and a long harvest window. Cut outer leaves at the base and the plant keeps producing from the center for months — through light frost, and in mild regions straight into the next spring. Tolerates heat better than spinach and part shade better than most greens. Handsome enough to plant in a flower bed.',
    price_cents: 325,
    seed_count: '100 seeds',
    days_to_maturity: '55-60 days',
    sun: 'Full sun to part shade',
    spacing: '8-12 in.',
    planting_depth: '1/2 in.',
    height: '18-24 in.',
    origin_note: 'A traditional mix of long-grown European chard selections.',
    stock: 205,
    featured: false,
    accent: '#d4562f',
    motif: 'leaf',
  },
  {
    slug: 'black-beauty-eggplant',
    name: 'Black Beauty Eggplant',
    botanical_name: 'Solanum melongena',
    category: 'Vegetables',
    blurb: 'Glossy near-black globes, heavy in the hand, on compact upright plants.',
    description:
      'The classic market eggplant — deep purple-black, one to three pounds each, four or five fruits to a plant. Flesh is creamy and mild with few seeds when picked before the skin dulls. Loves heat and resents cold soil, so wait until nights are reliably warm before setting plants out. Harvest with pruners; the calyx has spines and the stems do not snap cleanly.',
    price_cents: 375,
    seed_count: '25 seeds',
    days_to_maturity: '75-85 days',
    sun: 'Full sun',
    spacing: '18-24 in.',
    planting_depth: '1/4 in.',
    height: '24-30 in.',
    origin_note: 'In American seed catalogs since 1902.',
    stock: 115,
    featured: false,
    accent: '#4b3b6b',
    motif: 'squash',
  },
  {
    slug: 'genovese-basil',
    name: 'Genovese Basil',
    botanical_name: 'Ocimum basilicum',
    category: 'Herbs',
    blurb: 'Big cupped leaves, true pesto perfume, slow to bolt in the heat.',
    description:
      'The basil Liguria makes pesto from — large, slightly cupped leaves with a sweeter, less clove-like perfume than common sweet basil. Pinch the growing tips early and often to force branching, and take flower buds off the moment you see them; once it blooms, leaf production stops and the flavor turns sharp. Grows well in a pot on a sunny step.',
    price_cents: 300,
    seed_count: '200 seeds',
    days_to_maturity: '60-75 days',
    sun: 'Full sun',
    spacing: '10-12 in.',
    planting_depth: '1/4 in.',
    height: '18-24 in.',
    origin_note: 'The traditional pesto basil of Genoa, Italy.',
    stock: 230,
    featured: true,
    accent: '#4f8a3d',
    motif: 'herb',
  },
  {
    slug: 'bouquet-dill',
    name: 'Bouquet Dill',
    botanical_name: 'Anethum graveolens',
    category: 'Herbs',
    blurb: 'Heavy seed heads for pickling, feathery fronds for everything else.',
    description:
      'Bred for large flower umbels and abundant seed, which is exactly what you want when the cucumbers come in all at once. The fronds are just as good fresh on fish or potatoes. Sow directly where it will grow — dill has a taproot and sulks when transplanted — and sow again every three weeks for a continuous supply. Let one plant go to seed and you will have volunteers forever, which is a feature.',
    price_cents: 300,
    seed_count: '250 seeds',
    days_to_maturity: '45 days leaf, 70 seed',
    sun: 'Full sun',
    spacing: '8-10 in.',
    planting_depth: '1/4 in.',
    height: '30-36 in.',
    origin_note: 'A long-grown selection favored for pickling.',
    stock: 195,
    featured: false,
    accent: '#8a9a3d',
    motif: 'herb',
  },
  {
    slug: 'common-sage',
    name: 'Common Garden Sage',
    botanical_name: 'Salvia officinalis',
    category: 'Herbs',
    blurb: 'A woody perennial that will outlive most of the garden around it.',
    description:
      'Soft gray-green leaves on a shrubby perennial that comes back bigger every year and shrugs off drought once it is established. Sage wants sharp drainage above all else — more plants are lost to wet winter feet than to cold. Cut it back hard in spring to keep it from going woody and sparse in the middle. Flowers are lavender-blue and the bees find them immediately.',
    price_cents: 300,
    seed_count: '50 seeds',
    days_to_maturity: '75 days',
    sun: 'Full sun',
    spacing: '18-24 in.',
    planting_depth: '1/4 in.',
    height: '18-30 in.',
    origin_note: 'A Mediterranean native grown in kitchen gardens for centuries.',
    stock: 150,
    featured: false,
    accent: '#7d8c78',
    motif: 'herb',
  },
  {
    slug: 'calendula-resina',
    name: 'Calendula, Resina',
    botanical_name: 'Calendula officinalis',
    category: 'Flowers',
    blurb: 'Golden petals for salve and salad, blooming from early summer to hard frost.',
    description:
      'A high-resin strain selected for herbal use, with sticky calyxes and single-to-semi-double golden blooms. Petals are edible and go into salads, and the whole flower heads infuse into oil for salve. Deadhead — or better, keep harvesting — and it flowers relentlessly until a hard freeze. Self-sows politely and tolerates poor soil and cool weather without complaint.',
    price_cents: 325,
    seed_count: '50 seeds',
    days_to_maturity: '55-60 days',
    sun: 'Full sun to part shade',
    spacing: '12 in.',
    planting_depth: '1/4 in.',
    height: '18-24 in.',
    origin_note: 'Selected from traditional pot marigold for high resin content.',
    stock: 170,
    featured: false,
    accent: '#e59a1f',
    motif: 'flower',
  },
  {
    slug: 'hopi-black-dye-sunflower',
    name: 'Hopi Black Dye Sunflower',
    botanical_name: 'Helianthus annuus',
    category: 'Flowers',
    blurb: 'Towering stalks, gold petals, and seeds so dark they were used as dye.',
    description:
      'Eight-foot stalks carrying broad golden blooms above deep purple-black seeds, traditionally used by Hopi weavers as a dye for basketry and textiles. Birds will find the heads the moment they ripen, so cut and hang them to dry indoors if you want the seed. Plant along a north edge where the height will not shade the rest of the garden, and stake in windy sites.',
    price_cents: 375,
    seed_count: '30 seeds',
    days_to_maturity: '90-110 days',
    sun: 'Full sun',
    spacing: '18-24 in.',
    planting_depth: '1 in.',
    height: '6-8 ft.',
    origin_note:
      'Grown by the Hopi people as a dye plant; please grow it with that history in mind.',
    stock: 95,
    featured: true,
    accent: '#5b4a7d',
    motif: 'flower',
  },
  {
    slug: 'zinnia-state-fair-mix',
    name: 'Zinnia, State Fair Mix',
    botanical_name: 'Zinnia elegans',
    category: 'Flowers',
    blurb: 'Dinner-plate blooms on long stems. Cut them and you get more.',
    description:
      'Four-to-five-inch double blooms in scarlet, gold, rose, orange and cream on strong three-foot stems built for cutting. The more you cut, the more it branches and blooms — a single row will keep a vase full from July to frost and bring in every butterfly in the neighborhood. Give them air movement and water at the base to keep powdery mildew off the lower leaves late in the season.',
    price_cents: 325,
    seed_count: '50 seeds',
    days_to_maturity: '70-80 days',
    sun: 'Full sun',
    spacing: '12-18 in.',
    planting_depth: '1/4 in.',
    height: '30-36 in.',
    origin_note: 'A tall large-flowered mix long grown for exhibition and cutting.',
    stock: 200,
    featured: false,
    accent: '#d8456b',
    motif: 'flower',
  },
  {
    slug: 'first-garden-collection',
    name: 'First Garden Collection',
    botanical_name: '',
    category: 'Collections',
    blurb: 'Six forgiving varieties for a first season, with a planting plan that fits a 4x8 bed.',
    description:
      'For anyone starting out: Cherokee Purple tomato, Dragon Tongue bean, Lemon cucumber, Rainbow chard, Scarlet Nantes carrot, and Genovese basil — six varieties chosen because they germinate readily, tolerate a little neglect, and produce enough to feel like a real harvest. Ships with a one-page planting plan laid out for a 4x8 raised bed, including what to sow directly, what to start indoors, and roughly when.',
    price_cents: 1850,
    seed_count: '6 full packets',
    days_to_maturity: 'Varies by variety',
    sun: 'Full sun',
    spacing: 'See included plan',
    planting_depth: 'See included plan',
    height: 'Varies',
    origin_note: 'Our own selection, assembled from the varieties we hand out most often.',
    stock: 60,
    featured: true,
    accent: '#4a7c59',
    motif: 'packet',
  },
  {
    slug: 'pollinator-collection',
    name: 'Pollinator Patch Collection',
    botanical_name: '',
    category: 'Collections',
    blurb: 'Four flowers that keep something in bloom from June until the first hard frost.',
    description:
      'Calendula, State Fair zinnias, Hopi Black Dye sunflowers, and bouquet dill — chosen so that something is always flowering and the bloom times overlap rather than stacking up in one big July flush. Dill and calendula pull in the small parasitic wasps that go after garden pests; the zinnias and sunflowers handle butterflies and bees. Enough seed for roughly a 50 square foot patch.',
    price_cents: 1250,
    seed_count: '4 full packets',
    days_to_maturity: 'Varies by variety',
    sun: 'Full sun',
    spacing: 'See included plan',
    planting_depth: 'See included plan',
    height: '18 in. to 8 ft.',
    origin_note: 'Our own selection for overlapping bloom windows.',
    stock: 75,
    featured: false,
    accent: '#c98b3a',
    motif: 'packet',
  },
];
